---
- name: Clone repositories from GitLab
  hosts: all_server
  become: yes

  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Ensure destination directory for git repo exists
      file:
        path: /path/to/clone
        state: directory

    - name: Clone git repository
      git:
        repo: 'REPLACE_WITH_GITLAB_REPO_URL'
        dest: /path/to/clone
        version: main  # specify the branch or tag if necessary
        key_file: /path/to/ssh_key  # Specify the path to the private key
        accept_hostkey: yes

    - name: Ensure destination directory for git repo exists
      file:
        path: /path/to/clone
        state: directory

    - name: Clone r_site_app_new repository
      git:
        repo: 'REPLACE_WITH_GITLAB_REPO_URL'
        dest: /path/to/clone
        version: main  # specify the branch or tag if necessary
        key_file: /path/to/ssh_key  # Specify the path to the private key
        accept_hostkey: yes
