---
- name: Install Redis
  hosts: your_redis_servers
  become: yes

  tasks:
    - name: Import GPG key for Redis
      apt_key:
        url: https://packages.redis.io/gpg
        state: present

    - name: Add Redis repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb {{ ansible_distribution_release }} main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Redis
      apt:
        name: redis
        state: present
