---
- name: Update apt package index
  hosts: all_server
  become: yes

  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes
      register: update_result

    - name: Print update result
      debug:
        var: update_result
